# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'PTGSDKExample' do
  pod 'Ads-CN-Beta', '4.8.0.3'
  pod 'GDTMobSDK', '4.14.10'
  pod 'FancyAd','1.0.5'
  pod 'KSAdSDK', '3.3.13'
  pod 'PTGJAdSDK','1.2.0'      #
  pod 'Masonry'
  pod 'CocoaDebug'
end
