# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'PTGSDKExample' do
#  pod 'Ads-CN', '3.4.2.8'
#  pod 'GDTMobSDK', '4.12.3'
#  pod 'FancyAd', '1.0.0'
#  pod 'Masonry'
#  pod 'CocoaDebug','1.6.2'
#  pod 'KSAdSDK','3.3.9.3'
end
