
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
target 'PTGAdDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for PTGAdDemo
  pod 'GDTMobSDK', '4.11.11'
  pod 'Bytedance-UnionAD', '3.2.6.2'
  pod 'PTGAdFramework', '~> 1.2.3'
#  pod 'AFNetworking'
end
