
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
target 'PTGAdDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for PTGAdDemo
#  pod 'GDTMobSDK', '4.12.1'
#  pod 'Bytedance-UnionAD', '3.2.6.2'
  pod 'PTGAdFramework', '1.4.1'
  pod 'PTGIFLYAd'
end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      end
    end
  end
end
